### ISSUE TITLE
[Bug]: Typo in boilerplate code 

### ISSUE THREAD

**Issue by ankur-gupta** [rungalileo/feedback#1]
### What happened?

For text classification task:

<img width="1568" alt="Screenshot 2023-03-31 at 5 24 25 PM" src="https://user-images.githubusercontent.com/7110058/229256286-5950f044-2f95-4d6c-861d-c0e25eaadb86.png">

### What browsers are you seeing the problem on?

Firefox

**Comment by setu4993** [comment]
Hey @ankur-gupta, sorry it took a while to respond here. Curious what page you're seeing that on?

**Comment by ankur-gupta** [comment]
Sorry, I can't remember. It's been a while since I did this but I used one of the template examples.

**Comment by setu4993** [comment]
Thanks @ankur-gupta! We found it and it'll be fixed on the new release.
